language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iSzudED/8W+QAZ2lrm7/FyHTxs/ibhtIXEl7ClrRZiP1ggHoNkppyOln516D0VlMwB7DDi/ONixvDFXy3/L9xQ3/9MilD+oc0ebs4mBcQwb4qxbVgEiqADtNEmeqOad1q3HUahNtphLY/S8ekXtiEk4O09yhcojOVbHmRdtm41jxsXKN6KpG5y7EArmUwdgCR3X0WZkKNQKCpNnmlOekDD2Iuz+FaUmKbe5Z5KoukQaDemrSwFEHUf6U4eZM0YlIuJLpGaccF32zukJsLDRjg0mJUVjWFuddauuJh72ADpXGMjvz8cTkKDi/xmiRWFWQAhsR7i4NvHFiMd/MfAPcHWYEk93pZtPpLCDJe2rQtOQ/h2hBx6f5OzUPjN+jWnlAF0Ys/Bx8WguDIhk0FQxGxQ326wLakZcdPxzlfxmTTzS5jwr8Z1NDdQ3EDlNp8ufMrqTEcmmlOBuwEnfDGSD3I/CQCnxPol3xGqiYeRf6XqiON8+QSm8P/pus+9J0yH7zodWw5uDuKuQQaBSbULG2akHuv2Gwo0SPTrV9nQmYmioD0Qv5YWKojmvX7JfRSo0B7zdDjE34eHL908SejwJ6WDz18Seomk78jmizO3Psvzxuu4LWg2k6FrHWKOhxuhlk7c1EAhdyXu8bryRhLDylkHS2crdplpEcOuWaef3r4mQ=
  file:
    - 'doctype.js'
    - 'doctype.min.js'
  on:
    tags: true
