language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: C+Tik0b5C2WUR0SIHh99zFkOKB/HrTNIccn8sZzp4E3z2wStNE9xk8veUGwwdxps5PUotEeAJwSPu3waE4lLxZ2b9vJq5sQPTQ+5NNEqhRjOdNEyVGynvuWI/zZPXN3lhy43TQT9uHq3wYLu4UqPmOVSEynmQWFNy40/M+LRglxRaJ38evA470pMYk6Uq6D0q7EAg8IqJHjKb3xwruaA8CwGRhCp2il5NMuuDydMk9Rn5Rkf96blT67k5b8Rv783wGV8zijVecjz0kKYwdKIMqyBYSLpkRjg+IZJTEASo0jq5iOrdC15f6X45jjrUK5aUC9Sk9KZrhSirSWS+e5sqSdEAkOgiMwyXOeRFofdg3CXKFDdcpVaTAgkj5ouCVNlJqfjxJIbn9a/gpc8SA9IJtNkGlgpgXWalXN2UhsBqe1zuzwte+dfNbB+dCcfTvMmXKp6Ln23RtzCHSnaiaVcTeC90yLCC1ztmY8JvIcEFupztPIl+6pwcmn8Ww4OUTzt8P3+lka14wUXegBZiVPQ5ZnOyZzTAQ/5Ai9LrF2m0MYUU4ABuG84JmCx4tNAnl5GscPJ1i4WiC/5enzOPy8qaodfjahBrR9b+yzROpHdKv8TmQIvfsFDL+O64uSfr0UVav8JpFcCAK2bOKW8DNbaWhxGNDLcx78GZtYvzlYLA3Q=
  file:
    - "doctype.js"
    - "doctype.min.js"
  on:
    tags: true
